apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresinstances-prod.aws.database.platform.io
  labels:
    provider: aws
    database: postgresql
    environment: prod
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: database.platform.io/v1alpha1
    kind: XPostgresInstance
  
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # DB Subnet Group
          - name: dbsubnetgroup
            base:
              apiVersion: rds.aws.upbound.io/v1beta1
              kind: SubnetGroup
              spec:
                forProvider:
                  region: us-east-1
                  description: "Subnet group for RDS instance (Prod)"
                  subnetIds:
                    - subnet-0d314833cc14dec38
                    - subnet-09d20accdc77294a1
                    - subnet-08c008d1a577bc4a3
            
          # Security Group for RDS
          - name: securitygroup
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: SecurityGroup
              spec:
                forProvider:
                  region: us-east-1
                  description: "Security group for RDS PostgreSQL (Prod)"
                  vpcId: vpc-021a41484acb9a32a
            
          # Security Group Rule - Allow PostgreSQL from VPC
          - name: securitygrouprule
            base:
              apiVersion: ec2.aws.upbound.io/v1beta1
              kind: SecurityGroupRule
              spec:
                forProvider:
                  region: us-east-1
                  type: ingress
                  fromPort: 5432
                  toPort: 5432
                  protocol: tcp
                  cidrBlocks:
                    - "10.1.0.0/16"  # Prod VPC CIDR
                  securityGroupIdSelector:
                    matchControllerRef: true
            
          # RDS Instance
          - name: rdsinstance
            base:
              apiVersion: rds.aws.upbound.io/v1beta1
              kind: Instance
              metadata:
                labels:
                  database: postgresql
              spec:
                forProvider:
                  region: us-east-1
                  engine: postgres
                  engineVersion: "15"
                  instanceClass: db.t3.medium
                  allocatedStorage: 20
                  storageType: gp3
                  storageEncrypted: true
                  username: postgres
                  dbName: bookings
                  publiclyAccessible: false
                  skipFinalSnapshot: true
                  dbSubnetGroupNameSelector:
                    matchControllerRef: true
                  vpcSecurityGroupIdSelector:
                    matchControllerRef: true
                  passwordSecretRef:
                    name: db-password
                    namespace: crossplane-system
                    key: password
                writeConnectionSecretToRef:
                  namespace: default
            connectionDetails:
            connectionDetails:
              - type: FromConnectionSecretKey
                name: username
                fromConnectionSecretKey: username
              - type: FromConnectionSecretKey
                name: password
                fromConnectionSecretKey: password
              - type: FromConnectionSecretKey
                name: endpoint
                fromConnectionSecretKey: endpoint
              - type: FromConnectionSecretKey
                name: port
                fromConnectionSecretKey: port
              - type: FromConnectionSecretKey
                name: address
                fromConnectionSecretKey: address
            patches:
              # Map size parameter to instance class
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.size
                toFieldPath: spec.forProvider.instanceClass
                transforms:
                  - type: map
                    map:
                      small: db.t3.micro
                      medium: db.t3.small
                      large: db.t3.medium
              
              # Map storage parameter
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.storage
                toFieldPath: spec.forProvider.allocatedStorage
              
              # Map version parameter
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.version
                toFieldPath: spec.forProvider.engineVersion
              
              # Set connection secret name
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "%s-conn"
