apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresinstances.database.platform.io
spec:
  group: database.platform.io
  names:
    kind: XPostgresInstance
    plural: xpostgresinstances
  claimNames:
    kind: PostgresInstance
    plural: postgresinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
    - address
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    size:
                      type: string
                      description: "Database size: small, medium, or large"
                      enum:
                        - small
                        - medium
                        - large
                      default: small
                    storage:
                      type: integer
                      description: "Storage size in GB"
                      default: 20
                      minimum: 20
                      maximum: 100
                    version:
                      type: string
                      description: "PostgreSQL version"
                      default: "15"
                  required:
                    - size
              required:
                - parameters
            status:
              type: object
              properties:
                endpoint:
                  type: string
                  description: "Database endpoint"
                port:
                  type: integer
                  description: "Database port"
