apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booking-service-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sikander098/astronomy-platform.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
